language: python
sudo: required
branches:
  only:
    - pyqt4_only
python:
  # We don't actually use the Travis Python, but this keeps it organized.
#  - "2.6"
#  - "2.7"
#  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install: 
  - chmod +rx install_dependencies.sh
  - ./install_dependencies.sh
  - source ~/.bashrc
  - source activate test-environment
  
# command to run tests
script: 
  - python popupcad_tests/test_gui.py --qt4